language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
services:
  - redis-server
script: 
  - nosetests --with-cov
env:
  - SERVER_HOST="localhost"
  - PORT_NUMBER="3454"
  - DB_VALUE=0
